# Generated by Django 4.2.4 on 2023-10-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='is_sale',
            field=models.BooleanField(blank=True, default=False, verbose_name='En oferta'),
        ),
    ]
